/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./../components/layout/AppLayout.vue')['default']
    Card: typeof import('./../components/common/Card.vue')['default']
    CpButton: typeof import('./../components/common/CpButton.vue')['default']
    Empty: typeof import('./../components/common/Empty.vue')['default']
    Header: typeof import('./../components/layout/Header.vue')['default']
    Loading: typeof import('./../components/common/Loading.vue')['default']
    QRLogin: typeof import('./../components/business/QRLogin.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../components/layout/Sidebar.vue')['default']
    Skeleton: typeof import('./../components/common/Skeleton.vue')['default']
    StatusTag: typeof import('./../components/common/StatusTag.vue')['default']
  }
}
